apiVersion: v1
kind: Service
metadata:
  name: studentmarkservice-service
spec:
  type: NodePort
  ports:
    - port: 8100
      targetPort: 8100
      nodePort: 30100
  selector:
    app: studentmarkservice
